// <auto-generated />
namespace DSKviz.Dao.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _03FixCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_03FixCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201504201733266_03FixCategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
