// <auto-generated />
namespace DSKviz.Dao.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _02AddAuth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_02AddAuth));
        
        string IMigrationMetadata.Id
        {
            get { return "201504191936232_02AddAuth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
